CXX ?= c++
CXXFLAGS ?= -std=c++17 -Wall -Wextra -Werror -pedantic -O2

HOST_BUILD := .build-host
CORE_SOURCES := \
	source/core/engine.cpp \
	source/core/locale.cpp \
	source/core/size.cpp
TEST_BINARY := $(HOST_BUILD)/core-tests

.PHONY: test clean-host

test: $(TEST_BINARY)
	@$(TEST_BINARY)

$(TEST_BINARY): $(CORE_SOURCES) tests/core_tests.cpp
	@mkdir -p $(HOST_BUILD)
	$(CXX) $(CXXFLAGS) -Iinclude $(CORE_SOURCES) tests/core_tests.cpp -o $@

clean-host:
	rm -rf $(HOST_BUILD)
