#!/usr/bin/env python3
"""Generate portable and Switch-specific C++ catalog tables."""

from __future__ import annotations

import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "data" / "monsters.json"
CORE_OUTPUT = ROOT / "source" / "core" / "catalog.cpp"
ALIAS_OUTPUT = ROOT / "source" / "platform" / "switch" / "monster_aliases.cpp"


def cpp_string(value: str) -> str:
    return json.dumps(value, ensure_ascii=False)


def generate_core(monsters: list[dict]) -> str:
    rows = []
    for monster in monsters:
        names = monster["names"]
        crowns = monster["crowns"]
        rows.append(
            "    {"
            f'{monster["id"]}, {cpp_string(monster["key"])}, '
            "{"
            f'{cpp_string(names["en"])}, '
            f'{cpp_string(names["zh-Hans"])}, '
            f'{cpp_string(names["ja"])}'
            "}, "
            f'{monster["baseSizeX100"]}, '
            f'{crowns["miniPercent"]}, '
            f'{crowns["silverPercent"]}, '
            f'{crowns["goldPercent"]}, '
            f'{"true" if monster["variableSize"] else "false"}'
            "},"
        )

    return f"""// Generated by tools/generate_catalog.py. Do not edit manually.
#include "mhgu/core/catalog.hpp"

#include <cstring>

namespace mhgu::core {{
namespace {{

constexpr MonsterDefinition kMonsters[] = {{
{chr(10).join(rows)}
}};

}}  // namespace

const MonsterDefinition* find_monster(const MonsterId id) {{
    for (const auto& monster : kMonsters) {{
        if (monster.id == id) {{
            return &monster;
        }}
    }}
    return nullptr;
}}

const MonsterDefinition* find_monster_by_key(const char* key) {{
    if (key == nullptr) {{
        return nullptr;
    }}
    for (const auto& monster : kMonsters) {{
        if (std::strcmp(monster.key, key) == 0) {{
            return &monster;
        }}
    }}
    return nullptr;
}}

const MonsterDefinition* monster_catalog() {{
    return kMonsters;
}}

std::size_t monster_catalog_size() {{
    return sizeof(kMonsters) / sizeof(kMonsters[0]);
}}

}}  // namespace mhgu::core
"""


def generate_aliases(monsters: list[dict]) -> str:
    rows = []
    for monster in monsters:
        for alias in monster["switchAliases"]:
            rows.append(
                "    {"
                f'{alias["rawId"]}, {monster["id"]}, '
                f'{"true" if alias["hyper"] else "false"}'
                "},"
            )
    rows.sort()

    return f"""// Generated by tools/generate_catalog.py. Do not edit manually.
#include "mhgu/platform/switch/monster_aliases.hpp"

namespace mhgu::platform::switch_adapter {{
namespace {{

constexpr MonsterAlias kAliases[] = {{
{chr(10).join(rows)}
}};

}}  // namespace

const MonsterAlias* find_monster_alias(const std::uint32_t raw_id) {{
    for (const auto& alias : kAliases) {{
        if (alias.raw_id == raw_id) {{
            return &alias;
        }}
    }}
    return nullptr;
}}

const MonsterAlias* monster_aliases() {{
    return kAliases;
}}

std::size_t monster_alias_count() {{
    return sizeof(kAliases) / sizeof(kAliases[0]);
}}

}}  // namespace mhgu::platform::switch_adapter
"""


def main() -> None:
    data = json.loads(SOURCE.read_text(encoding="utf-8"))
    monsters = data["monsters"]

    CORE_OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    ALIAS_OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    CORE_OUTPUT.write_text(generate_core(monsters), encoding="utf-8")
    ALIAS_OUTPUT.write_text(generate_aliases(monsters), encoding="utf-8")
    print(f"Generated catalog for {len(monsters)} monsters")


if __name__ == "__main__":
    main()
