#!/usr/bin/env python3
"""Compile normalized catalog and locale JSON into dependency-free C++ tables."""

from __future__ import annotations

import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
CATALOG_PATH = ROOT / "data" / "catalog" / "monsters.json"
LOCALE_PATHS = {
    "en": ROOT / "data" / "locales" / "en.json",
    "zh-Hans": ROOT / "data" / "locales" / "zh-Hans.json",
    "ja": ROOT / "data" / "locales" / "ja.json",
}
CORE_OUTPUT = ROOT / "source" / "generated" / "catalog.cpp"
MESSAGES_OUTPUT = ROOT / "source" / "generated" / "messages.cpp"
ALIAS_OUTPUT = ROOT / "source" / "generated" / "switch_aliases.cpp"

UI_KEYS = [
    "title",
    "notRunning",
    "noMonsters",
    "health",
    "size",
    "language",
    "automatic",
    "sizePreset",
    "sizeLock",
    "off",
    "mini",
    "silver",
    "gold",
    "experimental",
    "scan",
    "scanning",
    "ready",
    "unsupported",
    "writeFailed",
    "hyper",
]


def cpp_string(value: str) -> str:
    return json.dumps(value, ensure_ascii=False)


def load_inputs() -> tuple[dict, dict[str, dict]]:
    catalog = json.loads(CATALOG_PATH.read_text(encoding="utf-8"))
    locales = {
        name: json.loads(path.read_text(encoding="utf-8"))
        for name, path in LOCALE_PATHS.items()
    }
    expected = {monster["key"] for monster in catalog["monsters"]}
    for name, locale in locales.items():
        actual = set(locale["monsters"])
        if actual != expected:
            missing = sorted(expected - actual)
            extra = sorted(actual - expected)
            raise ValueError(
                f"{name} monster keys differ; missing={missing}, extra={extra}"
            )
        missing_ui = [key for key in UI_KEYS if key not in locale["ui"]]
        if missing_ui:
            raise ValueError(f"{name} is missing UI keys: {missing_ui}")
    return catalog, locales


def generate_core(catalog: dict, locales: dict[str, dict]) -> str:
    rows = []
    for monster in catalog["monsters"]:
        key = monster["key"]
        crowns = monster["crowns"]
        rows.append(
            "    {"
            f'{monster["id"]}, {cpp_string(key)}, '
            "{"
            f'{cpp_string(locales["en"]["monsters"][key])}, '
            f'{cpp_string(locales["zh-Hans"]["monsters"][key])}, '
            f'{cpp_string(locales["ja"]["monsters"][key])}'
            "}, "
            f'{monster["baseSizeX100"]}, '
            f'{crowns["miniPercent"]}, '
            f'{crowns["silverPercent"]}, '
            f'{crowns["goldPercent"]}, '
            f'{"true" if monster["variableSize"] else "false"}'
            "},"
        )

    return f"""// Generated by tools/generate_catalog.py. Do not edit.
#include "mhgu/core/catalog.hpp"

#include <cstring>

namespace mhgu::core {{
namespace {{

constexpr MonsterDefinition kMonsters[] = {{
{chr(10).join(rows)}
}};

}}  // namespace

const MonsterDefinition* find_monster(const MonsterId id) {{
    for (const auto& monster : kMonsters) {{
        if (monster.id == id) {{
            return &monster;
        }}
    }}
    return nullptr;
}}

const MonsterDefinition* find_monster_by_key(const char* key) {{
    if (key == nullptr) {{
        return nullptr;
    }}
    for (const auto& monster : kMonsters) {{
        if (std::strcmp(monster.key, key) == 0) {{
            return &monster;
        }}
    }}
    return nullptr;
}}

const MonsterDefinition* monster_catalog() {{
    return kMonsters;
}}

std::size_t monster_catalog_size() {{
    return sizeof(kMonsters) / sizeof(kMonsters[0]);
}}

}}  // namespace mhgu::core
"""


def generate_messages(locales: dict[str, dict]) -> str:
    rows = []
    for key in UI_KEYS:
        rows.append(
            "    {"
            f'{cpp_string(locales["en"]["ui"][key])}, '
            f'{cpp_string(locales["zh-Hans"]["ui"][key])}, '
            f'{cpp_string(locales["ja"]["ui"][key])}'
            "},"
        )
    return f"""// Generated by tools/generate_catalog.py. Do not edit.
#include "mhgu/core/messages.hpp"

#include <cstddef>

namespace mhgu::core {{
namespace {{

constexpr const char* kMessages[][3] = {{
{chr(10).join(rows)}
}};

}}  // namespace

const char* ui_message(const UiMessage message, const Locale locale) {{
    const auto row = static_cast<std::size_t>(message);
    auto column = std::size_t{{0}};
    if (locale == Locale::SimplifiedChinese) {{
        column = 1;
    }} else if (locale == Locale::Japanese) {{
        column = 2;
    }}
    return kMessages[row][column];
}}

}}  // namespace mhgu::core
"""


def generate_aliases(catalog: dict) -> str:
    rows = [
        (
            int(monster["switch"]["rawId"], 16),
            monster["id"],
        )
        for monster in catalog["monsters"]
    ]
    rows.sort()
    entries = [
        f"    {{0x{raw_id:06X}, {monster_id}}},"
        for raw_id, monster_id in rows
    ]
    return f"""// Generated by tools/generate_catalog.py. Do not edit.
#include "mhgu/platform/switch/monster_aliases.hpp"

namespace mhgu::platform::switch_adapter {{
namespace {{

constexpr MonsterAlias kAliases[] = {{
{chr(10).join(entries)}
}};

}}  // namespace

const MonsterAlias* find_monster_alias(const std::uint32_t raw_id) {{
    for (const auto& alias : kAliases) {{
        if (alias.raw_id == raw_id) {{
            return &alias;
        }}
    }}
    return nullptr;
}}

const MonsterAlias* monster_aliases() {{
    return kAliases;
}}

std::size_t monster_alias_count() {{
    return sizeof(kAliases) / sizeof(kAliases[0]);
}}

}}  // namespace mhgu::platform::switch_adapter
"""


def main() -> None:
    catalog, locales = load_inputs()
    outputs = {
        CORE_OUTPUT: generate_core(catalog, locales),
        MESSAGES_OUTPUT: generate_messages(locales),
        ALIAS_OUTPUT: generate_aliases(catalog),
    }
    for path, content in outputs.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
    print(f"Generated C++ tables for {len(catalog['monsters'])} monsters")


if __name__ == "__main__":
    main()
