name: build

on:
  push:
  pull_request:

jobs:
  host-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Run portable tests
        run: make -f Makefile.host test

  switch:
    runs-on: ubuntu-latest
    container: devkitpro/devkita64:latest
    steps:
      - uses: actions/checkout@v7
        with:
          submodules: recursive
      - name: Build overlay
        run: make -j2
      - uses: actions/upload-artifact@v7
        with:
          name: mhgu-overlay
          path: mhgu-overlay.ovl
          if-no-files-found: error
